# Generated by Django 3.0.4 on 2020-03-22 19:34

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modificação')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Biografia')),
                ('image', stdimage.models.StdImageField(upload_to='authors', verbose_name='Imagem')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Falecimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
