# Generated by Django 3.0.4 on 2020-03-28 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookshelfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modificação')),
                ('status', models.CharField(choices=[('reading', 'Estou lendo'), ('read', 'Já li'), ('want', 'Quero ler'), ('stop', 'Abandonei')], max_length=7, verbose_name='Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Item da prateleira',
                'verbose_name_plural': 'Itens da prateleira',
            },
        ),
    ]
