# Generated by Django 3.0.4 on 2020-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modificação')),
                ('name', models.CharField(max_length=100, verbose_name='Língua')),
            ],
            options={
                'verbose_name': 'Língua',
                'verbose_name_plural': 'Línguas',
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
