# Generated by Django 3.0.4 on 2020-03-25 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to='users', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Biografia')),
                ('favorite_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre', verbose_name='Gênero favorito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pefil do usuário',
                'verbose_name_plural': 'Perfis de usuários',
            },
        ),
    ]
