# Generated by Django 3.0.4 on 2020-03-25 04:59

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book'),
        ('accounts', '0002_auto_20200325_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre', verbose_name='Gênero favorito'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=stdimage.models.StdImageField(upload_to='users', verbose_name='Imagem de perfil'),
        ),
    ]
