# Generated by Django 3.0.4 on 2020-03-28 18:21

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200325_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=stdimage.models.StdImageField(default='default.png', upload_to='users', verbose_name='Imagem de perfil'),
        ),
    ]
