# Generated by Django 3.0.4 on 2020-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200328_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Biografia'),
            preserve_default=False,
        ),
    ]
